config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'public/main#homepage'

  get 'login' => 'sessions#new', as: :login
  post 'login' => 'sessions#create', as: :create_login
  get 'logout' => 'sessions#destroy', as: :logout

  namespace :public do
    get 'homepage' => 'main#homepage', as: :homepage
    get 'signup' => 'signups#new', as: :signup
    post 'signup' => 'signups#create', as: :create_signup
  end

  namespace :account do
    get 'homepage' => 'main#homepage', as: :homepage
    resources :trackers do
      member do
        post 'dismiss_welcome_message' => 'trackers#dismiss_welcome_message', as: :dismiss_welcome_message
      end
    end
    resources :trips
  end

  mount Resque::Server.new, :at => "/resque"
end

app/views/layouts/_flash_messages.html.erb
<% if flash.any? %>
  <% flash.select{|k,v| %w{error failure danger info notice success alert warning}.include?(k)}.each do |type, msg| %>
    <div class="alert alert-<%= flash_class(type) %> alert-dismissible m-t-sm m-b-sm" data-alert="true">
      <% unless flash[:important] %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      <% end %>
      <% if msg.is_a? Array %>
        <% msg.each do |message| %>
          <ul>
            <li><%= message %></li>
          </ul>
        <% end %>
      <% else %>
        <%= msg %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <% if @current_user %>
    <a class="navbar-brand" href="#">UK ILR Day Counter</a>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <% if @current_user %>
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= @current_user.email %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Account", account_homepage_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Log Out", logout_path, class: "dropdown-item" %>
          </div>
        <% else %>
          <%= link_to "Log In", '#', class: "btn btn-sm btn-secondary login-button", data: { toggle: "modal", target: "#login-form-modal" } %>
          <%= link_to "Sign Up", '#', class: "btn btn-sm btn-secondary signup-button", data: { toggle: "modal", target: "#signup-form-modal" } %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebDayCounter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
  </head>

  <body>
    <%= render '/layouts/navbar' %>
    <%= render '/layouts/flash_messages' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/empty.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebDayCounter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>